#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: Init repos list to empty list
  set_fact:
    repos_to_add: []

- debug: var=repos_to_add
- debug: var=base_repos
- debug: var=cloud_update_repos
- debug: var=sles_test_repos
- debug: var=cloud_test_repos

- name: Gather repos to add
  set_fact:
    repos_to_add: "{{ repos_to_add + item.repo }}"
  when: "item.enabled | default(True)"
  loop:
    - repo: "{{ base_repos }}"
    - repo: "{{ cloud_update_repos }}"
      enabled: "{{ cloud_update_repos_enabled }}"
    - repo: "{{ sles_test_repos }}"
      enabled: "{{ sles_test_repos_enabled }}"
    - repo: "{{ cloud_test_repos }}"
      enabled: "{{ cloud_test_repos_enabled }}"

- debug: var=repos_to_add
- debug: var=zypper_repo_state
- debug: var=zypper_repo_enabled

- name: Ensure repo directory exists
  file:
    state: directory
    path: "{{ local_repos_base_dir }}/{{ zypper_repo_name }}"
  loop: "{{ repos_to_add }}"

- name: Rsync repos that are frequently updated
  synchronize:
    mode: pull
    src: "rsync://{{ clouddata_server }}/cloud/repos/{{ ansible_architecture }}/{{ item }}/"
    dest: "{{ local_repos_base_dir }}/{{ zypper_repo_name }}"
    rsync_opts:
      - "--sparse"
      - "--hard-links"
      - "--fuzzy"
      - "--delete-delay"
  delegate_to: "{{ inventory_hostname }}"
  loop: "{{ repos_to_sync }}"
  register: sync_result
  retries: 5
  until: sync_result.rc != 24
  delay: 300
  when:
    - zypper_repo_state != "absent"

- name: Add Pool tag to relevant rsync'd repos
  lineinfile:
    path: "{{ local_repos_base_dir }}/{{ zypper_repo_name }}/suse/repodata/repomd.xml"
    insertafter: "<tags>"
    line: "    <repo>obsproduct://build.suse.de/SUSE:SLE-{{ setup_distro_major_version }}-SP{{ setup_distro_release }}:Update:Products:Cloud{{ setup_cloud_release[-1] }}/{{ cloud_brand | lower }}/{{ setup_cloud_release[-1] }}/POOL/x86_64</repo>"
  loop: "{{ repos_to_sync }}"
  when:
    - item.endswith('-devel') or item.endswith('-devel-staging')

- name: Add Updates tag to relevant rsync'd repos
  lineinfile:
    path: "{{ local_repos_base_dir }}/{{ zypper_repo_name }}/suse/repodata/repomd.xml"
    insertafter: "<tags>"
    line: "    <repo>obsrepository://build.suse.de/SUSE:Updates:{{ cloud_brand | replace('SUSE-', '') }}:{{ setup_cloud_release[-1] }}:x86_64/update</repo>"
  loop: "{{ repos_to_sync }}"
  when:
    - item.endswith('-devel') or item.endswith('-devel-staging')

- name: Mount repos that are not frequently updated
  mount:
    src: "{{ clouddata_server }}:/srv/nfs/repos/{{ ansible_architecture }}/{{ item }}"
    path: "{{ local_repos_base_dir }}/{{ item }}"
    opts: ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock,x-systemd.automount,noauto
    fstype: nfs
    state: mounted
  loop: "{{ repos_to_mount }}"
  when:
    - zypper_repo_state == "present"

- name: Add zypper repos
  zypper_repository:
    name: "{{ zypper_repo_name }}"
    repo: "{{ local_repos_base_dir }}/{{ zypper_repo_name }}"
    enabled: "{{ zypper_repo_enabled }}"
    state: "{{ zypper_repo_state }}"
  loop: "{{ repos_to_add }}"
  notify:
    - Refresh all repos
  when:
    - zypper_repo_state == "present"
    - zypper_repo_enabled == "yes"

- name: Disable zypper repos if required
  zypper_repository:
    name: "{{ zypper_repo_name }}"
    repo: "{{ local_repos_base_dir }}/{{ zypper_repo_name }}"
    enabled: "{{ zypper_repo_enabled }}"
    state: "{{ zypper_repo_state }}"
  loop: "{{ repos_to_add }}"
  notify:
    - Refresh all repos
  when:
    - zypper_repo_enabled != "yes"

- name: Remove zypper repos if required
  zypper_repository:
    name: "{{ zypper_repo_name }}"
    state: "{{ zypper_repo_state }}"
  loop: "{{ repos_to_add }}"
  notify:
    - Refresh all repos
  when:
    - zypper_repo_state != "present"

- name: Unmount NFS repos that are no longer required
  mount:
    src: "{{ clouddata_server }}:/srv/nfs/repos/{{ ansible_architecture }}/{{ item }}"
    path: "{{ local_repos_base_dir }}/{{ item }}"
    opts: ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock,x-systemd.automount,noauto
    fstype: nfs
    state: absent
  loop: "{{ repos_to_mount }}"
  when:
    - false  # need to keep them mounted for now
    - zypper_repo_state != "present"
